services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    restart: always
    volumes:
      - ./config.json:/etc/v2ray/config.json
    ports:
      - "1080:1080"
  
  app:
    image: curlimages/curl
    depends_on:
      - v2ray
    environment:
      - HTTP_PROXY=http://v2ray:1080
      - HTTPS_PROXY=http://v2ray:1080
    command: ["curl", "-x", "http://v2ray:1080", "http://ipinfo.io"]
